# Generated by Django 3.2.6 on 2021-08-30 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='unknow',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
