# Generated by Django 3.2.6 on 2021-08-30 01:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_unknow'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='unknow',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='short_intro',
            new_name='title',
        ),
        migrations.CreateModel(
            name='skills',
            fields=[
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
        ),
    ]
