# Generated by Django 3.2.6 on 2021-08-30 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210830_0102'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='skills',
            new_name='Skill',
        ),
    ]
