# Generated by Django 3.2.6 on 2021-08-31 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_skills_skill'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='social_youtube',
            new_name='social_stackoverflow',
        ),
    ]
