# Generated by Django 3.2.6 on 2021-09-10 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_messages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message', to='users.profile'),
        ),
    ]
